### PR TITLE
iOS bundle key restrictions

### PR DESCRIPTION
**Pull request by rkelly2001**
feat: send bundle identifier in request header, allowing bundle identifier key restrictions to be enabled.

### CODE REVIEW

**Comment by Igor-Palaguta** [comment]
Hello @rkelly2001 

Thanks for feedback! Could not find any official documentation about this header. Do you have?

Please check if this works for you https://github.com/Igor-Palaguta/YoutubeEngine/commit/9ab83b63c71499746fb1cab54e6855bc26001570

**Comment by rkelly2001** [comment]
welcome, nice library setup.  I saw a lot of people complaining with the same issue, then I found this https://github.com/GoogleCloudPlatform/ios-docs-samples/issues/11

**Comment by rkelly2001** [comment]
awesome, your change works.  I had to reference below get my pod to update:
"pod 'YoutubeEngine', :git => 'https://github.com/Igor-Palaguta/YoutubeEngine.git'"

**Comment by Igor-Palaguta** [comment]
welcome)

**Pull request closed without merging**
